language: go
go:
- 1.11
before_install:
- go get github.com/axw/gocov/gocov
- go get github.com/mattn/goveralls
- if ! go get github.com/golang/tools/cmd/cover; then go get golang.org/x/tools/cmd/cover;
  fi
script:
- cd $TRAVIS_BUILD_DIR && $HOME/gopath/bin/goveralls -service=travis-ci -repotoken $COVERALLS_TOKEN
- cd $TRAVIS_BUILD_DIR && go test
- cd $TRAVIS_BUILD_DIR && GOOS=linux GOARCH=amd64 go build -o deb-simple_linux
- cd $TRAVIS_BUILD_DIR && GOOS=darwin GOARCH=amd64 go build -o deb-simple_darwin
- cd $TRAVIS_BUILD_DIR && GOOS=windows GOARCH=amd64 go build -o deb-simple_windows.exe
